In [7]:
import numpy as np
import pandas as pd



In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
def f(a1, a2):
    return a1+a1

map(f, a, b)

In [3]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a*b

array([2, 4, 6])

In [14]:
a = np.array([[1,-2,3],[3,-1,-2]])
def f(a1):
    return max(0, a1)

c = np.array(list(map(f, a.flatten('C')))).reshape(2,3)
print(c)



[[1 0 3]
 [3 0 0]]


In [10]:
def f(a):
    return 1 / (1 + np.exp(a))

In [11]:
ad = 




[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

In [13]:
np.exp(3)

20.085536923187668