In [1]:
import numpy as np
import pandas as pd



In [2]:
df = pd.read_csv('./data/test/test_data.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 10: invalid start byte

In [5]:
print(df)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fe

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
def f(a1, a2):
    return a1+a1

map(f, a, b)

In [9]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a*b

array([2, 4, 6])

In [52]:
a = np.array([[1,-2,3],[3,-1,-2]])
def f(a1):
    return max(0, a1)

b = a.flatten('C')
c = np.array(list(map(f, b))).reshape(2,3)
print(c)



[[1 0 3]
 [3 0 0]]


In [56]:
1 / (1 + np.e(-a[1,1]))

TypeError: 'float' object is not callable